name: Docker build & push

on:
  workflow_dispatch:
  push:
    tags:
      - 'release-*'

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version
        id: get_version
        run: |
          VERSION="${GITHUB_REF_NAME#release-}"
          echo "Version is $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  bash-build:
    needs: extract-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push (bash)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/apash-bash.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/apash_fork:bash-${{ needs.extract-version.outputs.version }}

  zsh-build:
    needs: extract-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push (zsh)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/apash-zsh.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/apash_fork:zsh-${{ needs.extract-version.outputs.version }}
