name: Docker build & push

on:
  workflow_dispatch:
  push:
    tags:
      - 'release-*'

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version
        id: get_version
        run: |
          VERSION="${GITHUB_REF_NAME#release-}"
          echo "Version is $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  bash-build:
    needs: extract-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: build docker image
        id: docker_build_bash
        run: |
          VERSION="${{ needs.extract-version.outputs.version }}"
          USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
          docker build . -f docker/apash-bash.dockerfile -t "$USERNAME/apash_fork:bash-$VERSION"

      - name: push docker image to docker hub
        id: docker_push_bash
        run: |
          VERSION="${{ needs.extract-version.outputs.version }}"
          USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
          PASSWORD="${{ secrets.DOCKERHUB_PASSWORD }}"
          docker login -u "$USERNAME" -p "$PASSWORD" && docker push "$USERNAME/apash_fork:bash-$VERSION"
