name: Docker build & push

on:
  workflow_dispatch:
  push:
    tags:
      - 'release-*'
    branches:
      - 'main'
      - 'docker-workflow-integration'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: |
          TAG_NAME="${GITHUB_REF_NAME}"
          VERSION="${TAG_NAME#release-}"
          echo "Version is $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
    
      - name: build docker images
        id: docker builds
        run: |
          docker build docker/ -f apash-bash.dockerfile -t apash-fork-bash:$VERSION
          docker build docker/ -f apash-zsh.dockerfile -t apash-fork-zsh:$VERSION
          docker images
